import { JSDOM } from 'jsdom';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const ROOT = new URL('..', import.meta.url).pathname.replace(/\/$/, '');
const html = readFileSync(ROOT + '/options/options.html', 'utf8').replace(/<script[\s\S]*?<\/script>/g, '');
const w = new JSDOM(html, { url: 'chrome-extension://abc/options/options.html' }).window;
for (const k of ['window', 'document', 'Node', 'Event']) Object.defineProperty(globalThis, k, { value: k === 'window' ? w : w[k], configurable: true });
Object.defineProperty(globalThis, 'navigator', { value: { storage: { estimate: async () => ({ usage: 5e6, quota: 1e9 }) } }, configurable: true });
w.HTMLDialogElement.prototype.showModal = function () { this.open = true; setTimeout(() => this.close('ok')); };
w.HTMLDialogElement.prototype.close = function (v) { this.returnValue = v ?? ''; this.dispatchEvent(new w.Event('close')); };
const mk = () => { const d = {}; return { d, async get(k) { return k in d ? { [k]: d[k] } : {}; }, async set(o) { Object.assign(d, o); }, async remove(k) { delete d[k]; } }; };
globalThis.chrome = { storage: { local: mk(), session: mk(), onChanged: { addListener() {} } }, runtime: { getManifest: () => ({ version: '1.0.0' }) }, permissions: { request: async () => true } };
globalThis.indexedDB = undefined;
globalThis.fetch = async () => ({ ok: true, json: async () => ({ models: [{ name: 'models/gemini-3-flash', supportedGenerationMethods: ['generateContent'] }] }) });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const $ = (s) => w.document.querySelector(s);
await import(ROOT + '/options/options.js');
await sleep(100);
assert.equal($('#model').value, 'gemini-2.5-flash');
assert.equal($('#keywordCount').value, '12');
$('#defaultLink').value = 'javascript:alert(1)';
$('#form').dispatchEvent(new w.Event('submit', { cancelable: true }));
await sleep(50);
assert.ok($('#defaultLinkErr').textContent.length > 0);
$('#defaultLink').value = 'myshop.com';
$('#apiKey').value = '  AIzaTESTKEY9999  ';
$('#boards').value = 'A\nB\n\nA';
$('#keywordCount').value = '99';
$('input[name="keyStorage"][value="session"]').checked = true;
$('#testKey').click();
await sleep(50);
assert.match($('#keyStatus').textContent, /Key works/);
assert.ok([...$('#model').options].some((o) => o.value === 'gemini-3-flash'));
$('#form').dispatchEvent(new w.Event('submit', { cancelable: true }));
await sleep(100);
const s = chrome.storage.local.d.settings;
assert.equal(s.defaultLink, 'https://myshop.com/');
assert.deepEqual(s.boards, ['A', 'B']);
assert.equal(s.keywordCount, 30);
assert.equal(chrome.storage.session.d.geminiApiKey, 'AIzaTESTKEY9999');
assert.equal(chrome.storage.local.d.geminiApiKey, undefined);
assert.match($('#keyStatus').textContent, /AIza…9999/);
$('#forgetKey').click();
await sleep(50);
assert.equal(chrome.storage.session.d.geminiApiKey, undefined);
console.log('OPTIONS SMOKE TEST PASSED');
process.exit(0);
